### PR TITLE
Me liek colours :'-)

### PR DESCRIPTION
**Pull request by g3wanghc**
screen shot 2016-08-03 at 10 55 14 am

### CODE REVIEW

**Comment by arkon** [comment]
This doesn't seem to bring any useful functionality to the table.

**Comment by g3wanghc** [comment]
Fair enough. I was just curious why the icon was in black on white. :P

**Comment by arkon** [comment]
That's just how Chrome 52+ displays extensions if they don't have a popup. You can hide them from their context menus.

**Comment by g3wanghc** [comment]
Yeah, I was pretty curious. 

I didn't know how chrome extensions worked, and just made a popup for fun.

**Pull request closed without merging**
